import { useWallet } from '@txnlab/use-wallet'
import Head from 'next/head'
import Account from 'components/Account'
import Connect from 'components/Connect'
import Navbar from 'components/Navbar'
import Spinner from 'components/Spinner'
import Transact from 'components/Transact'

export default function Home() {
  const { isReady } = useWallet()

  const renderPage = () => {
    if (!isReady) {
      return (
        <div className="flex items-center justify-center py-[25vh]">
          <Spinner />
        </div>
      )
    }

    return (
      <main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 pt-10 pb-48 lg:pb-16 space-y-12">
        <Connect />
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
          <Account />
          <Transact />
        </div>
      </main>
    )
  }

  return (
    <>
      <Head>
        <title>Next.js use-wallet Demo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      {renderPage()}
    </>
  )
}
